# Generated by Django 5.0.3 on 2024-05-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCianRent',
            fields=[
                ('tcr_id', models.AutoField(db_column='tcr_id', primary_key=True, serialize=False)),
                ('tcr_url', models.URLField(blank=True, db_column='tc_url', null=True, verbose_name='URL')),
                ('tcr_area', models.FloatField(blank=True, db_column='tc_area', max_length=25, null=True, verbose_name='Площадь')),
                ('tcr_floor', models.FloatField(blank=True, db_column='tc_floor', max_length=25, null=True, verbose_name='Этаж')),
                ('tcr_floors', models.FloatField(blank=True, db_column='tc_floors', max_length=25, null=True, verbose_name='Этажность')),
                ('tcr_additional_info', models.JSONField(blank=True, db_column='tc_additional_info', null=True, verbose_name='Дополнительная информация')),
                ('tcr_cost', models.FloatField(blank=True, db_column='tc_cost', max_length=25, null=True, verbose_name='Стоимость')),
                ('tcr_address', models.ForeignKey(blank=True, db_column='tc_address', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pa.tbladdresses')),
            ],
            options={
                'verbose_name': 'Запись циан аренда',
                'verbose_name_plural': 'Записи циана аренда',
                'db_table': 'tbl_cian_rent',
                'ordering': ['tcr_id'],
            },
        ),
        migrations.CreateModel(
            name='TblCianSale',
            fields=[
                ('tcs_id', models.AutoField(db_column='tcs_id', primary_key=True, serialize=False)),
                ('tcs_url', models.URLField(blank=True, db_column='tcs_url', null=True, verbose_name='URL')),
                ('tcs_area', models.FloatField(blank=True, db_column='tcs_area', max_length=25, null=True, verbose_name='Площадь')),
                ('tcs_floor', models.FloatField(blank=True, db_column='tcs_floor', max_length=25, null=True, verbose_name='Этаж')),
                ('tcs_floors', models.FloatField(blank=True, db_column='tcs_floors', max_length=25, null=True, verbose_name='Этажность')),
                ('tcs_additional_info', models.JSONField(blank=True, db_column='tcs_additional_info', null=True, verbose_name='Дополнительная информация')),
                ('tcs_cost', models.FloatField(blank=True, db_column='tcs_cost', max_length=25, null=True, verbose_name='Стоимость')),
                ('tcs_address', models.ForeignKey(blank=True, db_column='tcs_address', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pa.tbladdresses')),
            ],
            options={
                'verbose_name': 'Запись циана продажа',
                'verbose_name_plural': 'Записи циана продажа',
                'db_table': 'tbl_cian_sale',
                'ordering': ['tcs_id'],
            },
        ),
        migrations.DeleteModel(
            name='TblCian',
        ),
    ]
