# Generated by Django 5.0.3 on 2024-05-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa', '0002_tblcianrent_tblciansale_delete_tblcian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcianrent',
            name='tcr_additional_info',
            field=models.JSONField(blank=True, db_column='tcr_additional_info', null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='tblcianrent',
            name='tcr_address',
            field=models.ForeignKey(blank=True, db_column='tcr_address', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pa.tbladdresses'),
        ),
        migrations.AlterField(
            model_name='tblcianrent',
            name='tcr_area',
            field=models.FloatField(blank=True, db_column='tcr_area', max_length=25, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='tblcianrent',
            name='tcr_cost',
            field=models.FloatField(blank=True, db_column='tcr_cost', max_length=25, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='tblcianrent',
            name='tcr_floor',
            field=models.FloatField(blank=True, db_column='tcr_floor', max_length=25, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='tblcianrent',
            name='tcr_floors',
            field=models.FloatField(blank=True, db_column='tcr_floors', max_length=25, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='tblcianrent',
            name='tcr_url',
            field=models.URLField(blank=True, db_column='tcr_url', null=True, verbose_name='URL'),
        ),
    ]
